### PR TITLE
Add state_getKeysPaged rpc call

### PR DESCRIPTION
**Pull request by alistair-singh**
Added the required rpc call. The tests do not cover the complete code path. But this is good enough to start working with in the relayer.

### CODE REVIEW

**Comment by alistair-singh** [comment]
Linter was failing with:
```
rpc/state/get_keys.go:34:30: `prefix` can be `github.com/snowfork/go-substrate-rpc-client/v3/types.Hexer` (interfacer)
func (s *State) GetKeysPaged(prefix types.StorageKey,
                             ^
rpc/state/get_keys.go:35:16: `startKey` can be `github.com/snowfork/go-substrate-rpc-client/v3/types.Hexer` (interfacer)
        count uint32, startKey *types.StorageKey,
```

As far as I can tell we do not want to use the Hexer interface here.

**Comment by alistair-singh** [comment]
I have tested this with e2e tests and all pass. The unit tests added are very simplistic and basically just test type marshalling.

**Comment by alistair-singh** [comment]
Ran the `make test-dockerized` command and the same failures happen on `main` branch.

**Review by vgeddes — APPROVED** [review]
Looks good!

**Comment by vgeddes** [comment]
Also yeah, no need to worry about the other unit tests not passing 100% in Github Actions. They are failing for a pre-existing issue. I also never run the linter on GSRPC.

**Pull request merged**
